import type { Block } from 'payload'

export const FeaturesBlock: Block = {
  slug: 'features-block',
  labels: {
    singular: 'Icon Block',
    plural: 'Icons Block',
  },
  fields: [
    {
      name: 'features',
      type: 'array',
      label: 'Features',
      required: true,
      fields: [
        {
          name: 'icon',
          type: 'select',
          label: 'Icon',
          options: [
            { label: 'Star', value: 'ri-star-line' },
            { label: 'Rocket', value: 'ri-rocket-line' },
            { label: 'Lightbulb', value: 'ri-lightbulb-line' },
            { label: 'Heart', value: 'ri-heart-line' },
            { label: 'Check', value: 'ri-check-line' },
            { label: 'Home', value: 'ri-home-line' },
            { label: 'User', value: 'ri-user-line' },
            { label: 'Settings', value: 'ri-settings-line' },
            { label: 'Search', value: 'ri-search-line' },
            { label: 'Camera', value: 'ri-camera-line' },
            { label: 'Phone', value: 'ri-phone-line' },
            { label: 'Mail', value: 'ri-mail-line' },
            { label: 'Calendar', value: 'ri-calendar-line' },
            { label: 'Map', value: 'ri-map-line' },
            { label: 'Lock', value: 'ri-lock-line' },
            { label: 'Unlock', value: 'ri-unlock-line' },
            { label: 'Bell', value: 'ri-bell-line' },
            { label: 'Chat', value: 'ri-chat-line' },
            { label: 'Notification', value: 'ri-notification-line' },
            { label: 'Cloud', value: 'ri-cloud-line' },
            { label: 'Download', value: 'ri-download-line' },
            { label: 'Upload', value: 'ri-upload-line' },
            { label: 'Folder', value: 'ri-folder-line' },
            { label: 'File', value: 'ri-file-line' },
            { label: 'Edit', value: 'ri-edit-line' },
            { label: 'Delete', value: 'ri-delete-line' },
            { label: 'Save', value: 'ri-save-line' },
            { label: 'Play', value: 'ri-play-line' },
            { label: 'Pause', value: 'ri-pause-line' },
            { label: 'Stop', value: 'ri-stop-line' },
            { label: 'Rewind', value: 'ri-rewind-line' },
            { label: 'Forward', value: 'ri-forward-line' },
            { label: 'Volume Up', value: 'ri-volume-up-line' },
            { label: 'Volume Down', value: 'ri-volume-down-line' },
            { label: 'Mute', value: 'ri-volume-mute-line' },
            { label: 'Battery', value: 'ri-battery-line' },
            { label: 'Wifi', value: 'ri-wifi-line' },
            { label: 'Bluetooth', value: 'ri-bluetooth-line' },
            { label: 'Power', value: 'ri-power-line' },
            { label: 'Shopping Cart', value: 'ri-shopping-cart-line' },
            { label: 'Gift', value: 'ri-gift-line' },
            { label: 'Star Half', value: 'ri-star-half-line' },
            { label: 'Star Fill', value: 'ri-star-fill' },
            { label: 'Heart Fill', value: 'ri-heart-fill' },
            { label: 'Check Fill', value: 'ri-check-fill' },
            { label: 'Home Fill', value: 'ri-home-fill' },
            { label: 'User Fill', value: 'ri-user-fill' },
            { label: 'Settings Fill', value: 'ri-settings-fill' },
            { label: 'Search Fill', value: 'ri-search-fill' },
            { label: 'Arrow Up', value: 'ri-arrow-up-line' },
            { label: 'Arrow Down', value: 'ri-arrow-down-line' },
            { label: 'Arrow Left', value: 'ri-arrow-left-line' },
            { label: 'Arrow Right', value: 'ri-arrow-right-line' },
            { label: 'Book', value: 'ri-book-line' },
            { label: 'Bookmark', value: 'ri-bookmark-line' },
            { label: 'Briefcase', value: 'ri-briefcase-line' },
            { label: 'Building', value: 'ri-building-line' },
            { label: 'Car', value: 'ri-car-line' },
            { label: 'Cart', value: 'ri-cart-line' },
            { label: 'Clipboard', value: 'ri-clipboard-line' },
            { label: 'Clock', value: 'ri-clock-line' },
            { label: 'Compass', value: 'ri-compass-line' },
            { label: 'Dashboard', value: 'ri-dashboard-line' },
            { label: 'Database', value: 'ri-database-line' },
            { label: 'Earth', value: 'ri-earth-line' },
            { label: 'Eye', value: 'ri-eye-line' },
            { label: 'Flag', value: 'ri-flag-line' },
            { label: 'Folder Open', value: 'ri-folder-open-line' },
            { label: 'Globe', value: 'ri-globe-line' },
            { label: 'Hand', value: 'ri-hand-line' },
            { label: 'Headphone', value: 'ri-headphone-line' },
            { label: 'Heart Pulse', value: 'ri-heart-pulse-line' },
            { label: 'Inbox', value: 'ri-inbox-line' },
            { label: 'Key', value: 'ri-key-line' },
            { label: 'Leaf', value: 'ri-leaf-line' },
            { label: 'Link', value: 'ri-link-line' },
            { label: 'List', value: 'ri-list-line' },
            { label: 'Location', value: 'ri-map-pin-line' },
            { label: 'Lock Fill', value: 'ri-lock-fill' },
            { label: 'Mail Fill', value: 'ri-mail-fill' },
            { label: 'Map Fill', value: 'ri-map-fill' },
            { label: 'Notification Fill', value: 'ri-notification-fill' },
            { label: 'Phone Fill', value: 'ri-phone-fill' },
            { label: 'Play Fill', value: 'ri-play-fill' },
            { label: 'Pause Fill', value: 'ri-pause-fill' },
            { label: 'Stop Fill', value: 'ri-stop-fill' },
            { label: 'Rewind Fill', value: 'ri-rewind-fill' },
            { label: 'Forward Fill', value: 'ri-forward-fill' },
            { label: 'Volume Up Fill', value: 'ri-volume-up-fill' },
            { label: 'Volume Down Fill', value: 'ri-volume-down-fill' },
            { label: 'Mute Fill', value: 'ri-volume-mute-fill' },
            { label: 'Battery Fill', value: 'ri-battery-fill' },
            { label: 'Wifi Fill', value: 'ri-wifi-fill' },
            { label: 'Bluetooth Fill', value: 'ri-bluetooth-fill' },
            { label: 'Power Fill', value: 'ri-power-fill' },
            { label: 'Shopping Cart Fill', value: 'ri-shopping-cart-fill' },
            { label: 'Gift Fill', value: 'ri-gift-fill' },
            { label: 'Star Half Fill', value: 'ri-star-half-fill' },
            { label: 'Arrow Up Fill', value: 'ri-arrow-up-fill' },
            { label: 'Arrow Down Fill', value: 'ri-arrow-down-fill' },
            { label: 'Arrow Left Fill', value: 'ri-arrow-left-fill' },
            { label: 'Arrow Right Fill', value: 'ri-arrow-right-fill' },
            { label: 'Book Fill', value: 'ri-book-fill' },
            { label: 'Bookmark Fill', value: 'ri-bookmark-fill' },
            { label: 'Briefcase Fill', value: 'ri-briefcase-fill' },
            { label: 'Building Fill', value: 'ri-building-fill' },
            { label: 'Car Fill', value: 'ri-car-fill' },
            { label: 'Cart Fill', value: 'ri-cart-fill' },
            { label: 'Clipboard Fill', value: 'ri-clipboard-fill' },
            { label: 'Clock Fill', value: 'ri-clock-fill' },
            { label: 'Compass Fill', value: 'ri-compass-fill' },
            { label: 'Dashboard Fill', value: 'ri-dashboard-fill' },
            { label: 'Database Fill', value: 'ri-database-fill' },
            { label: 'Earth Fill', value: 'ri-earth-fill' },
            { label: 'Eye Fill', value: 'ri-eye-fill' },
            { label: 'Flag Fill', value: 'ri-flag-fill' },
            { label: 'Folder Open Fill', value: 'ri-folder-open-fill' },
            { label: 'Globe Fill', value: 'ri-globe-fill' },
            { label: 'Hand Fill', value: 'ri-hand-fill' },
            { label: 'Headphone Fill', value: 'ri-headphone-fill' },
            { label: 'Heart Pulse Fill', value: 'ri-heart-pulse-fill' },
            { label: 'Inbox Fill', value: 'ri-inbox-fill' },
            { label: 'Key Fill', value: 'ri-key-fill' },
            { label: 'Leaf Fill', value: 'ri-leaf-fill' },
            { label: 'Link Fill', value: 'ri-link-fill' },
            { label: 'List Fill', value: 'ri-list-fill' },
            { label: 'Location Fill', value: 'ri-map-pin-fill' },
          ],
          required: true,
        },
        {
          name: 'title',
          type: 'text',
          label: 'Title',
          required: true,
        },
        {
          name: 'description',
          type: 'textarea',
          label: 'Description',
          required: true,
        },
      ],
    },
  ],
}
