import type { Block } from 'payload'

export const TableBlock: Block = {
  slug: 'table',
  interfaceName: 'TableBlock',
  fields: [
    {
      name: 'columns',
      type: 'array',
      label: 'Columns',
      required: true,
      minRows: 1,
      fields: [
        {
          name: 'header',
          type: 'text',
          label: 'Header',
          required: true,
        },
      ],
    },
    {
      name: 'rows',
      type: 'array',
      label: 'Rows',
      required: true,
      minRows: 1,
      fields: [
        {
          name: 'blockType',
          type: 'hidden',
          defaultValue: 'defaultRow',
        },
        {
          name: 'cells',
          type: 'array',
          label: 'Cells',
          minRows: 1,
          fields: [
            {
              name: 'type',
              type: 'select',
              label: 'Type',
              required: true,
              options: [
                { label: 'Text', value: 'text' },
                { label: 'Number', value: 'number' },
                { label: 'Chip', value: 'chip' },
                { label: 'Date', value: 'date' },
                { label: 'Percentage Circle', value: 'views' },
                { label: 'Growth', value: 'growth' },
                { label: 'Author', value: 'author' },
              ],
            },
            {
              name: 'textSubtype',
              type: 'select',
              label: 'Text Subtype',
              options: [
                { label: 'Bold', value: 'bold' },
                { label: 'Medium', value: 'medium' },
                { label: 'Normal', value: 'normal' },
              ],
              defaultValue: 'normal',
              admin: {
                condition: (_, siblingData) => siblingData?.type === 'text',
              },
              required: true,
            },
            {
              name: 'statusType',
              type: 'select',
              label: 'Chip Type',
              options: [
                { label: 'Neutral', value: 'neutral' },
                { label: 'Success', value: 'success' },
                { label: 'Warning', value: 'warning' },
                { label: 'Error', value: 'error' },
                { label: 'CWC', value: 'cwc' },
                { label: 'WW', value: 'ww' },
              ],
              admin: {
                condition: (_, siblingData) => siblingData?.type === 'chip',
              },
            },
            {
              name: 'showDot',
              type: 'checkbox',
              label: 'Show Dot',
              admin: {
                condition: (_, siblingData) => siblingData?.type === 'chip',
              },
            },
            {
              name: 'preIcon',
              type: 'select',
              label: 'Pre Icon',
              options: [
                { label: 'None', value: '' },
                { label: 'Star', value: 'ri-star-line' },
                { label: 'Rocket', value: 'ri-rocket-line' },
                { label: 'Lightbulb', value: 'ri-lightbulb-line' },
                { label: 'Heart', value: 'ri-heart-line' },
                { label: 'Check', value: 'ri-check-line' },
                { label: 'User', value: 'ri-user-line' },
                { label: 'Settings', value: 'ri-settings-line' },
                { label: 'Search', value: 'ri-search-line' },
                { label: 'Camera', value: 'ri-camera-line' },
                { label: 'Phone', value: 'ri-phone-line' },
                { label: 'Mail', value: 'ri-mail-line' },
                { label: 'Calendar', value: 'ri-calendar-line' },
                { label: 'Map', value: 'ri-map-line' },
                { label: 'Lock', value: 'ri-lock-line' },
                { label: 'Bell', value: 'ri-bell-line' },
                { label: 'Chat', value: 'ri-chat-line' },
                { label: 'Cloud', value: 'ri-cloud-line' },
                { label: 'Download', value: 'ri-download-line' },
                { label: 'Upload', value: 'ri-upload-line' },
                { label: 'Folder', value: 'ri-folder-line' },
                { label: 'Edit', value: 'ri-edit-line' },
                { label: 'Delete', value: 'ri-delete-line' },
                { label: 'Save', value: 'ri-save-line' },
                { label: 'Play', value: 'ri-play-line' },
                { label: 'Pause', value: 'ri-pause-line' },
                { label: 'Stop', value: 'ri-stop-line' },
                { label: 'Arrow Up', value: 'ri-arrow-up-line' },
                { label: 'Arrow Down', value: 'ri-arrow-down-line' },
                { label: 'Arrow Left', value: 'ri-arrow-left-line' },
                { label: 'Arrow Right', value: 'ri-arrow-right-line' },
                { label: 'Book', value: 'ri-book-line' },
                { label: 'Bookmark', value: 'ri-bookmark-line' },
                { label: 'Briefcase', value: 'ri-briefcase-line' },
                { label: 'Building', value: 'ri-building-line' },
                { label: 'Car', value: 'ri-car-line' },
                { label: 'Clipboard', value: 'ri-clipboard-line' },
                { label: 'Clock', value: 'ri-clock-line' },
                { label: 'Compass', value: 'ri-compass-line' },
                { label: 'Dashboard', value: 'ri-dashboard-line' },
                { label: 'Database', value: 'ri-database-line' },
                { label: 'Earth', value: 'ri-earth-line' },
                { label: 'Eye', value: 'ri-eye-line' },
                { label: 'Flag', value: 'ri-flag-line' },
                { label: 'Globe', value: 'ri-globe-line' },
                { label: 'Hand', value: 'ri-hand-line' },
                { label: 'Headphone', value: 'ri-headphone-line' },
                { label: 'Inbox', value: 'ri-inbox-line' },
                { label: 'Key', value: 'ri-key-line' },
                { label: 'Leaf', value: 'ri-leaf-line' },
                { label: 'Link', value: 'ri-link-line' },
                { label: 'List', value: 'ri-list-line' },
                { label: 'Location', value: 'ri-map-pin-line' },
              ],
              admin: {
                condition: (_, siblingData) => siblingData?.type === 'chip',
              },
            },
            {
              name: 'postIcon',
              type: 'select',
              label: 'Post Icon',
              options: [
                { label: 'None', value: '' },
                { label: 'Star', value: 'ri-star-line' },
                { label: 'Rocket', value: 'ri-rocket-line' },
                { label: 'Lightbulb', value: 'ri-lightbulb-line' },
                { label: 'Heart', value: 'ri-heart-line' },
                { label: 'Check', value: 'ri-check-line' },
                { label: 'User', value: 'ri-user-line' },
                { label: 'Settings', value: 'ri-settings-line' },
                { label: 'Search', value: 'ri-search-line' },
                { label: 'Camera', value: 'ri-camera-line' },
                { label: 'Phone', value: 'ri-phone-line' },
                { label: 'Mail', value: 'ri-mail-line' },
                { label: 'Calendar', value: 'ri-calendar-line' },
                { label: 'Map', value: 'ri-map-line' },
                { label: 'Lock', value: 'ri-lock-line' },
                { label: 'Bell', value: 'ri-bell-line' },
                { label: 'Chat', value: 'ri-chat-line' },
                { label: 'Cloud', value: 'ri-cloud-line' },
                { label: 'Download', value: 'ri-download-line' },
                { label: 'Upload', value: 'ri-upload-line' },
                { label: 'Folder', value: 'ri-folder-line' },
                { label: 'Edit', value: 'ri-edit-line' },
                { label: 'Delete', value: 'ri-delete-line' },
                { label: 'Save', value: 'ri-save-line' },
                { label: 'Play', value: 'ri-play-line' },
                { label: 'Pause', value: 'ri-pause-line' },
                { label: 'Stop', value: 'ri-stop-line' },
                { label: 'Arrow Up', value: 'ri-arrow-up-line' },
                { label: 'Arrow Down', value: 'ri-arrow-down-line' },
                { label: 'Arrow Left', value: 'ri-arrow-left-line' },
                { label: 'Arrow Right', value: 'ri-arrow-right-line' },
                { label: 'Book', value: 'ri-book-line' },
                { label: 'Bookmark', value: 'ri-bookmark-line' },
                { label: 'Briefcase', value: 'ri-briefcase-line' },
                { label: 'Building', value: 'ri-building-line' },
                { label: 'Car', value: 'ri-car-line' },
                { label: 'Clipboard', value: 'ri-clipboard-line' },
                { label: 'Clock', value: 'ri-clock-line' },
                { label: 'Compass', value: 'ri-compass-line' },
                { label: 'Dashboard', value: 'ri-dashboard-line' },
                { label: 'Database', value: 'ri-database-line' },
                { label: 'Earth', value: 'ri-earth-line' },
                { label: 'Eye', value: 'ri-eye-line' },
                { label: 'Flag', value: 'ri-flag-line' },
                { label: 'Globe', value: 'ri-globe-line' },
                { label: 'Hand', value: 'ri-hand-line' },
                { label: 'Headphone', value: 'ri-headphone-line' },
                { label: 'Inbox', value: 'ri-inbox-line' },
                { label: 'Key', value: 'ri-key-line' },
                { label: 'Leaf', value: 'ri-leaf-line' },
                { label: 'Link', value: 'ri-link-line' },
                { label: 'List', value: 'ri-list-line' },
                { label: 'Location', value: 'ri-map-pin-line' },
              ],
              admin: {
                condition: (_, siblingData) => siblingData?.type === 'chip',
              },
            },
            // Value field for all types except author
            {
              name: 'value',
              type: 'text',
              label: 'Value',
              admin: {
                condition: (_, siblingData) => siblingData?.type !== 'author',
              },
            },
            // Percent field for views type
            {
              name: 'percent',
              type: 'number',
              label: 'Percentage of the circle (0-100)',
              min: 0,
              max: 100,
              admin: {
                condition: (_, siblingData) => siblingData?.type === 'views',
                step: 1,
              },
            },
            // Author-specific fields
            {
              name: 'name',
              type: 'text',
              label: 'Author Name',
              admin: {
                condition: (_, siblingData) => siblingData?.type === 'author',
              },
            },
            {
              name: 'role',
              type: 'text',
              label: 'Author Role',
              admin: {
                condition: (_, siblingData) => siblingData?.type === 'author',
              },
            },
            {
              name: 'media',
              type: 'upload',
              relationTo: 'media',
              label: 'Author Avatar',
              admin: {
                condition: (_, siblingData) => siblingData?.type === 'author',
              },
            },
          ],
        },
      ],
    },
  ],
}
